### ISSUE TITLE
Publish also OnSite API on packagist?

### ISSUE THREAD

**Issue by ThaDafinser** [WURFL/wurfl-cloud-client-php#4]
Hello,

since the `cloud API` finally reached composer support, is it also planned to publish a package for the PHP OnSite API?
https://filex.scientiamobile.com/user/index#products/OnSite/PHP_API/1.7.0.1

Currently in my package i use another package, but would like to use the original source if it's available over packagist, so there are will be no delay when a new wurfl version is released.

Used here https://github.com/ThaDafinser/UserAgentParser

**Comment by elliotfehr** [comment]
@ThaDafinser Since this is issue related to one of our OnSite offerings, are you able to submit this request on our public forum at https://scientiamobile.com/forum/viewforum.php?f=9
